events {}

http {
  server {
    listen 80;
    access_log /var/log/nginx/access.log;
    # server_name localhost:* attilaart.ch www.attilaart.ch;

    location ~ \.css {
      add_header Content-Type text/css;
    }

    location ~ \.js {
      add_header Content-Type text/css;
    }

    location / {
      root /app;
    }
  }
}
